CREATE DATABASE IF NOT EXISTS nassau_tickets CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nassau_tickets;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('PACIENTE','ATENDENTE') NOT NULL DEFAULT 'ATENDENTE',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
