CREATE DATABASE IF NOT EXISTS nassau_tickets CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nassau_tickets;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ATENDENTE','GESTOR') NOT NULL DEFAULT 'ATENDENTE',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS queue_control (
  id TINYINT PRIMARY KEY,
  last_type ENUM('SP','SE','SG') NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
INSERT IGNORE INTO queue_control (id,last_type) VALUES (1,NULL);

CREATE TABLE IF NOT EXISTS ticket_sequences (
  issue_date DATE NOT NULL,
  type ENUM('SP','SE','SG') NOT NULL,
  next_sequence SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY(issue_date,type)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tickets (
  id CHAR(36) PRIMARY KEY,
  number VARCHAR(20) NOT NULL UNIQUE,
  type ENUM('SP','SE','SG') NOT NULL,
  sequence_number SMALLINT UNSIGNED NOT NULL,
  issue_date DATE NOT NULL,
  status ENUM('EMITIDA','AGUARDANDO','CHAMADA','CHAMADA_NOVAMENTE','EM_ATENDIMENTO','ATENDIDA','NAO_COMPARECEU') NOT NULL,
  issued_at DATETIME NOT NULL,
  first_call_at DATETIME NULL,
  second_call_at DATETIME NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  counter SMALLINT UNSIGNED NULL,
  attendant_id CHAR(36) NULL,
  call_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ticket_queue(status,type,issued_at),
  INDEX idx_ticket_date(issue_date),
  CONSTRAINT fk_ticket_attendant FOREIGN KEY(attendant_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ticket_id CHAR(36) NULL,
  actor_user_id CHAR(36) NULL,
  counter SMALLINT UNSIGNED NULL,
  action VARCHAR(40) NOT NULL,
  occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata JSON NULL,
  INDEX idx_audit_ticket(ticket_id),
  INDEX idx_audit_date(occurred_at),
  CONSTRAINT fk_audit_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE SET NULL,
  CONSTRAINT fk_audit_user FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
