import {randomUUID} from 'node:crypto'
import {pool} from './db.js'
const VALID_TYPES=['SP','SE','SG']
function localHour(){return Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/Recife',hour:'2-digit',hour12:false}).format(new Date()))}
function ensureBusinessHours(){if(process.env.ENFORCE_BUSINESS_HOURS==='false') return; const hour=localHour(); if(hour<7||hour>=17) throw new Error('Atendimento fora do expediente. O horário de operação é das 07:00 às 17:00.')}

const nextType=async(conn)=>{const [[control]]=await conn.query('SELECT last_type FROM queue_control WHERE id=1 FOR UPDATE');const last=control?.last_type;const candidates=last==='SP'?['SE','SG','SP']:['SP','SE','SG'];for(const type of candidates){const [[row]]=await conn.query("SELECT id FROM tickets WHERE status='AGUARDANDO' AND type=? ORDER BY issued_at ASC LIMIT 1 FOR UPDATE",[type]);if(row)return {id:row.id,type}}return null}
export async function createTicket(type){ensureBusinessHours();if(!VALID_TYPES.includes(type))throw new Error('Tipo de senha inválido.');const conn=await pool.getConnection();try{await conn.beginTransaction();const today=new Date().toISOString().slice(0,10);await conn.query('INSERT INTO ticket_sequences(issue_date,type,next_sequence) VALUES(?,?,2) ON DUPLICATE KEY UPDATE next_sequence=next_sequence+1',[today,type]);const [[seq]] = await conn.query('SELECT next_sequence-1 AS sequence_number FROM ticket_sequences WHERE issue_date=? AND type=? FOR UPDATE',[today,type]);const number=`${today.slice(2).replaceAll('-','')}-${type}${String(seq.sequence_number).padStart(3,'0')}`;const id=randomUUID();const now=new Date();await conn.query("INSERT INTO tickets(id,number,type,sequence_number,issue_date,status,issued_at) VALUES(?,?,?,?,?,'AGUARDANDO',?)",[id,number,type,seq.sequence_number,today,now]);await conn.query("INSERT INTO audit_events(ticket_id,action,metadata) VALUES(?,'EMISSAO',?)",[id,JSON.stringify({type,number})]);await conn.commit();return {id,number,type,status:'AGUARDANDO',issued_at:now}}catch(e){await conn.rollback();throw e}finally{conn.release()}}
export async function callNext(userId,counter){ensureBusinessHours();if(!Number.isInteger(counter)||counter<1||counter>99)throw new Error('Guichê inválido.');const conn=await pool.getConnection();try{await conn.beginTransaction();const [[active]]=await conn.query("SELECT id,number,status FROM tickets WHERE attendant_id=? AND status IN ('CHAMADA','CHAMADA_NOVAMENTE','EM_ATENDIMENTO') ORDER BY first_call_at DESC LIMIT 1",[userId]);if(active&&active.status==='CHAMADA_NOVAMENTE'){await conn.query("UPDATE tickets SET status='NAO_COMPARECEU' WHERE id=?",[active.id]);await conn.query("INSERT INTO audit_events(ticket_id,actor_user_id,action,metadata) VALUES(?,?, 'NAO_COMPARECEU', ?)",[active.id,userId,JSON.stringify({reason:'segunda chamada sem comparecimento'})]);}else if(active){throw new Error(`Finalize o atendimento da senha ${active.number} antes de chamar outra.`)}const selected=await nextType(conn);if(!selected)throw new Error('Não há senhas aguardando atendimento.');const now=new Date();await conn.query("UPDATE tickets SET status='CHAMADA',first_call_at=?,call_count=1,counter=?,attendant_id=? WHERE id=? AND status='AGUARDANDO'",[now, counter,userId,selected.id]);await conn.query("UPDATE queue_control SET last_type=? WHERE id=1",[selected.type]);await conn.query("INSERT INTO audit_events(ticket_id,actor_user_id,counter,action) VALUES(?,?,?,'CHAMADA')",[selected.id,userId,counter]);await conn.commit();const [[ticket]]=await pool.query('SELECT * FROM tickets WHERE id=?',[selected.id]);return ticket}catch(e){await conn.rollback();throw e}finally{conn.release()}}
export async function repeatCall(userId,ticketId){const conn=await pool.getConnection();try{await conn.beginTransaction();const [[ticket]]=await conn.query("SELECT * FROM tickets WHERE id=? AND attendant_id=? FOR UPDATE",[ticketId,userId]);if(!ticket)throw new Error('Senha não encontrada para este atendente.');if(!['CHAMADA','CHAMADA_NOVAMENTE'].includes(ticket.status))throw new Error('A senha não pode ser chamada novamente neste estado.');if(ticket.call_count>=2){await conn.query("UPDATE tickets SET status='NAO_COMPARECEU' WHERE id=?",[ticketId]);await conn.query("INSERT INTO audit_events(ticket_id,actor_user_id,counter,action) VALUES(?,?,?,'NAO_COMPARECEU')",[ticketId,userId,ticket.counter]);await conn.commit();return {...ticket,status:'NAO_COMPARECEU'}}const now=new Date();await conn.query("UPDATE tickets SET status='CHAMADA_NOVAMENTE',second_call_at=?,call_count=2 WHERE id=?",[now,ticketId]);await conn.query("INSERT INTO audit_events(ticket_id,actor_user_id,counter,action) VALUES(?,?,?,'CHAMADA_NOVAMENTE')",[ticketId,userId,ticket.counter]);await conn.commit();const [[updated]]=await pool.query('SELECT * FROM tickets WHERE id=?',[ticketId]);return updated}catch(e){await conn.rollback();throw e}finally{conn.release()}}
export async function startTicket(userId,ticketId){const [result]=await pool.query("UPDATE tickets SET status='EM_ATENDIMENTO',started_at=NOW() WHERE id=? AND attendant_id=? AND status IN ('CHAMADA','CHAMADA_NOVAMENTE')",[ticketId,userId]);if(!result.affectedRows)throw new Error('A senha não está disponível para início.');await pool.query("INSERT INTO audit_events(ticket_id,actor_user_id,counter,action) SELECT id,attendant_id,counter,'INICIO_ATENDIMENTO' FROM tickets WHERE id=?",[ticketId]);const [[ticket]]=await pool.query('SELECT * FROM tickets WHERE id=?',[ticketId]);return ticket}
export async function finishTicket(userId,ticketId){const [result]=await pool.query("UPDATE tickets SET status='ATENDIDA',finished_at=NOW() WHERE id=? AND attendant_id=? AND status='EM_ATENDIMENTO'",[ticketId,userId]);if(!result.affectedRows)throw new Error('A senha não está em atendimento.');await pool.query("INSERT INTO audit_events(ticket_id,actor_user_id,counter,action) SELECT id,attendant_id,counter,'FINALIZACAO_ATENDIMENTO' FROM tickets WHERE id=?",[ticketId]);const [[ticket]]=await pool.query('SELECT * FROM tickets WHERE id=?',[ticketId]);return ticket}
export async function getQueue(){const [waiting]=await pool.query("SELECT id,number,type,status,issued_at FROM tickets WHERE status='AGUARDANDO' ORDER BY issued_at ASC");const [history]=await pool.query("SELECT t.id,t.number,t.type,t.counter,t.status,t.first_call_at AS called_at FROM tickets t WHERE t.first_call_at IS NOT NULL ORDER BY t.first_call_at DESC LIMIT 5");const [currentRows]=await pool.query("SELECT t.id,t.number,t.type,t.counter,t.status,t.call_count FROM tickets t WHERE t.first_call_at IS NOT NULL ORDER BY t.first_call_at DESC LIMIT 1");return {waiting,current:currentRows[0]||null,history}}
